travis:
  secure:
    BINSTAR_TOKEN: kZ7MjmxJBI3BICfymDEgOLFZwfp30vcb4R0qTWb5AxAiB/iKL/cKVkH1vF0m7eLsYHk0XlU8l/3x2KKc190uUGaGQs1Eum58EkwxKiLY5JanKEQkWTWXUmLAROsYtg8p6D0D8peNESWyApwGeMxizx0CEk9jNSLvkHN+IqrJaNMuFlz0K12mtFOQ5kTtF+s7ovLwXr0DH2790MleG7HsRS1Cdm11erSw0JIpE8i2lLGQUxY39eUceCoHSyEyAwBDnZydPhRoej1feDKtB0G1NsfGg/xUyvwGMATb1xd1fHQFfHsJ7N5tjACEFTjpjEDxmrbQSXIu8qDQJJJpeIaPRhiactJslctP62p8sxCguQTu+nLYzRk+q4DniBF5iL74+bCYY5GXuwIp6myxG7/ac+RGKrlME/DZ7rWIHGxLChzIKFWKtBQsAx+jKOF7DBlzVF2nRTlNU/v4+ArqFXokNYxsz2m8R/DnicWpjAgtCyBUscBTJNfJYoKavOWItogYqqmGUCoAItv8mMoIkl+5W5oZA/2sdMN2Fod3/uDtKoFQS+umV++uCElDrNWbVOXRP1Xy0LhKmwy5dI3LZ1DczLQL8tLhWTsr2gVq+9YrVKc6vEoUOYi6om+QRObDnbiuh2dVp5vOLQFXep6b2WD7Ktz8qjShqXVJM9GqnL7d/+c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
