travis:
  secure:
    BINSTAR_TOKEN: MyO365yWcuEA0V+2w6VkjZXovMb23/jPfUi7g4MWYl/9GaZbpFgkM7rotFbYs+F0O9vzUACcM+5LlfYqGSb9R1YboKcQ+s0Pvn70u1TUN4pOVg9/g8dOcpKu7rranL+jt5QHbBdsKxQ25Ma9b1N64guxOpuHly1ZSdKb6cpYlCNofoPhgE+YFtvboYYPTJcR9fumb47JBC6T0DId4uEqWoYT8qHWe7VrnZylR9yLVQgNO9aWkO5ibUDCQxNlQMqBF5J0pNpIvGN7muv6vLDDso6ti0bip6B0RSmapSy6wliV3N7tMMx+ySGHH9iM8kutV/KoNaCR2dJ5WEkvTDh0ycKHGLCytGaYaHlwSIX65ruQn2+LZR9aaW7mEfe5y3D7X5Cprjo2oU3JsjLMYOzJc/UkZvI4Vcj46h34ZuJ1w92ko6vRWQ2WxM9sGIKaMxjEo8weJgnOb2CXq6xU017g219l5hXTPnQ+/YIEqOIE/M4wZkLtidvpawqeHrvfyUMdSld8eHAHZMGelxCkpe46wQrzz277IrT0AqSTHdhsnzS5HmQpCMMqFt1PPvHEqeUqjRU4Dxd3/wjBdTtRdBYVdwiv/52/btJySgMtzvpLsoyGfwlgCYuJi20icbTkQGaGoHkdB1aS5DUn9Q6j+JptXd8rqn06ngzqv7nRd/FQBEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
